config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except:[:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length:  { minimum: 6, maximum: 100 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end    

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories
    
    validates :name, presence: true, uniqueness: true, length: { minimum: 4, maximum: 25 }


end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles, dependent: :destroy
    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
    validates(:email,
          presence: true,
          uniqueness: { case_sensitive: false },
          length: { maximum: 105 },
          # Verify email with ruby's standard library regex.
          format: { with: URI::MailTo::EMAIL_REGEXP })

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end 


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)

  end
  def show
  end
  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(permit_title_and_description)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was saved successfully."
      redirect_to @article
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    if @article.update(permit_title_and_description)
      flash[:notice] = "Article was succesfully updated"
      redirect_to @article
    else
      render 'edit', status: :unprocessable_entity
    end
  end
  
  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
  
  def set_article
    @article = Article.find(params[:id]) 
  end
  
  def permit_title_and_description
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
        flash[:alert] = "You can only edit or delete your own article"
        redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except:[:index, :show]
    
    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was succesfully created"
            redirect_to @category
        else
            render 'new'
        end
    end
    
    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end
    
    def show
        @category = Category.find(params[:id])
        @articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:notice] = "Category succesfully updated"
            redirect_to @category
        else
            render 'edit'
        end
    end

    private

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "Only admins can perform that action"
            redirect_to categories_path
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end    
    
    def about
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    
    end

    def create
            user = User.find_by(email: params[:session][:email].downcase)
            if user && user.authenticate(params[:session][:password])
                session[:user_id] = user.id
                flash[:notice] = "Logged in successfully"
                redirect_to user_path(user)
            else
              flash.now[:alert] = "There was something wrong"
              render 'new'
            end        
    end

    def destroy
      session[:user_id] = nil
      flash[:notice] = "You logged out"
      redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def new
        @user = User.new
    end

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    def edit
        
    end

    def show
        @articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    def update
        if @user.update(user_params)
            flash[:notice] = "Your Profile was successfully updated"
            redirect_to @user
        else
            render 'edit', status: :unprocessable_entity
        end
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "Welcome to the Alpha blog #{@user.username}, you have successfully sign up"
            redirect_to articles_path
        else
            render 'new'
        end
    end

    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "Account and all associated successfully deleted"
        redirect_to root_path

    end

    private
    
    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:alert] = "You can only edit or delete your own Profile"
            redirect_to @user
        end
    
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = { size: 80})
        email_address = user.email.downcase
        
        hash = Digest::SHA256.hexdigest(email_address)

        size = options[:size]

        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"

        image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")

    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if article.user %>
              By <%= link_to article.user.username, user_path(article.user) %>
              <% end %>
            <% if article.categories.any? %>
              <div class="mt-3">
                <%= render article.categories %>
              </div>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text text-black"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>                       
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
              <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {"turbo-method": :delete, "turbo-confirm": "estas seguro?"} %>
            <% end %>
          </div>
          <div class="card-footer text-body-secondary">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago,
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<body class="BodyHome">
  <div class="container">
    <div class="row justify-content-center">  
      <div class="col-10">
        <%= render 'shared/errors', obj: @article %>
        <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", data: { turbo: false }, local: true) do |f| %>
          <div class="form-group row">
            <%= f.label :title, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title" %>
            </div>
          </div>
          <br>
          <div class="form-group row">
            <%= f.label :description, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
            </div>
          </div>

          <div class="form-group row mt-4">
            <%= f.label :category, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.collection_select(:category_ids, Category.all, :id, :name, { prompt: "Make your selection from the list below(can be empty)"}, { multiple: true, size: 3, class: "form-select shadow rounded" }) %>
            </div>
          </div>
          
          <br>
          
          <div class="form-group row justify-content-center">
            <%= f.submit class: "btn btn-outline-light btn-lg botonCE"%>
          </div>

        <% end %>
      </div>
      
      <div class="text-center mb-3">
        <%= link_to '[ Back to listing page ]', articles_path, method: :get, class: "btn btn-link text-info" %>
      </div>
    </div>
  </div>
</body>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4 text-black">Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<body class="BodyHome">
<h1 class="text-center mt-4 text-black">Listing all articles</h1>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render partial: 'article' %>


<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

</body>

app/views/articles/new.html.erb
<h1 class="text-black mt-4 text-center">Create a new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="text-black text-center"><%= @article.title %></h1>
<div class="row justify-content-md-center">
<div class="col-8 mt-4">
  <div class="card text-center shadow mb-5 bg-white rounded">
    <div class="card-header font-italic">
      By <%= @article.user.username if @article.user %>
      <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
      <% if @article.categories.any? %>
        <div class="mt-3">
          <%= render @article.categories %>
        </div>
      <% end %>
    </div>
    <div class="card-body">
      <div class="card-text text-black"  style="text-align: left;">
        <%= simple_format(@article.description) %>
      </div>
      <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
        <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
        <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {"turbo-method": :delete, "turbo-confirm": "estas seguro?"} %>
      <% end %>
    </div>
    <div class="card-footer text-body-secondary">
      <small>Created <%= time_ago_in_words(@article.created_at) %> ago,
      edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
    </div>
  </div>
</div>
</div>
<div class="text-center">
    <%= link_to '[ Back to list page ]', articles_path, method: :get %>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill text-bg-info" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", data: { turbo: false }, local: true) do |f| %>
  <div class="form-group row mt-4">
    <%= f.label :name, class: "col-2 col-form-label text-light" %>
    <div class="col-10">
      <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a Category" %>
    </div>
  </div>
    
  <br>
  <div class="form-group row justify-content-center">
    <%= f.submit "Update article", class: "btn btn-outline-light btn-lg botonCE"%>
  </div>

<% end %>

app/views/categories/edit.html.erb
<h1 class="text-black mt-4 text-center">Edit category</h1>

<body class="BodyHome">
  <div class="container">
    <div class="row justify-content-center">  
      <div class="col-10">
        <%= render 'form' %>
      </div>
      
      <div class="text-center mb-3">
        <%= link_to '[ Back to Category page ]', category_path(@category), method: :get, class: "btn btn-link text-info" %>
      </div>
    </div>
  </div>
</body>

app/views/categories/index.html.erb
<h1 class="text-center mt-4 ">Categories</h1>

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
            <p class="card-text text-black"><%= pluralize(category.articles.count, "article") %></p>
            <% if logged_in? && current_user.admin? %> 
              <%= link_to "Edit Category", edit_category_path(category), class: "btn btn-outline-info" %>
            <% end %>
          </div>
          <div class="card-footer text-body-secondary">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago,
            edited <%= time_ago_in_words(category.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-black mt-4 text-center">Create category</h1>

<body class="BodyHome">
  <div class="container">
    <div class="row justify-content-center">  
      <div class="col-10">
        <%= render 'form' %>
      </div>
      
      <div class="text-center mb-3">
        <%= link_to '[ Back to listing categories page ]', categories_path, method: :get, class: "btn btn-link text-info" %>
      </div>
    </div>
  </div>
</body>

app/views/categories/show.html.erb
<h1 class="text-black mt-4 text-center">Category : <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
    <div class="text-center mt-4">
        <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info" %> 
    </div>
<% end %>

<h3 class="text-black mt-4 text-center">Articles</h3>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article', status: :unprocessable_entity %>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-3 bg-dark text-white fixed-bottom">
    <div class="container text-center">
        <small>Copyright &copy; <%= link_to "Gabriel Castro", "https://youtube.com", class: "text-white" %></small>
    </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
    <%= link_to "ALPHA BLOG", root_path, method: :get, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "Users", users_path, method: :get, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
            </a>
            <ul class="dropdown-menu">
            <% if logged_in? %>
                <li><%= link_to "Create Article", new_article_path, method: :get, class: "dropdown-item"%></li>
            <% end %>
            <li><%= link_to "View articles", articles_path, method: :get, class: "dropdown-item"%></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
            </a>
            <ul class="dropdown-menu">
            <% if logged_in? && current_user.admin? %>
                <li><%= link_to "Create new Category", new_category_path, method: :get, class: "dropdown-item"%></li>
            <% end %>
            <li><%= link_to "View Categories", categories_path, method: :get, class: "dropdown-item"%></li>
            </ul>
        </li>

        <% if logged_in? %>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= "(Admin)" if  current_user.admin? %> <%= current_user.username %>
                </a>
                <ul class="dropdown-menu">
                <li><%= link_to "View your profile", user_path(current_user), method: :get, class: "dropdown-item"%></li>
                <li><%= link_to "Edit your profile", edit_user_path(current_user), method: :get, class: "dropdown-item"%></li>
                <li><%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: {"turbo-method": :delete, "turbo-confirm": "Estas seguro?"} %></li>
                </ul>
            </li>
            <li class="nav-item">
                <%= button_to "Logout", logout_path, class: "nav-link", method: :delete %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to "Sign up", signup_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= button_to "Log in", login_path, class: "nav-link", method: :get %>
            </li>
        <% end %>
        </ul>
        <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Test App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body class="BodyHome">
    <%= render 'layouts/navigation' %>
    <div class="container">
        <% flash.each do |name, msg| %>
          <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
            <%= msg %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
    </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

<%= button_to 'Articles listing', articles_path, method: :get %>
<%= button_to 'Home page', root_path, method: :get %>
<%= button_to 'Alpha blog page', alpha_path, method: :get %>

app/views/pages/alpha.html.erb
<h1>Hello this is the alpha blog</h1>

<%= button_to 'Articles Listing', articles_path, method: :get %>
<%= button_to 'Home page', root_path, method: :get %>
<%= button_to 'About page', about_path, method: :get %>

app/views/pages/home.html.erb
<body class="BodyHome">
    <div class="container" id="home-container">
        <div class="jumbotron text-center">
            <h1 class="display-4 text-white">Alpha Blog</h1>
            <p class="lead text-white">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information</p>
            <hr class="my-4">
            <p class="text-white">It uses utility classes for typography and spacing to space content out within the larger container</p>
            <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
        </div>
    </div>
</body>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved </h4>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <ul>
            <% obj.errors.full_messages.each do |msg| %>
                <li> <%= msg %> </li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/users/_form.html.erb
<body class="BodyHome">
  <div class="container">
    <div class="row justify-content-center">  
      <div class="col-10">
        <%= render 'shared/errors', obj: @user %>
        <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", data: { turbo: false }, local: true) do |f| %>
          <div class="form-group row mt-4">
            <%= f.label :username, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
            </div>
          </div>
          <br>
          <div class="form-group row">
            <%= f.label :password, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
            </div>
          </div>
            
          <br>

          <div class="form-group row">
            <%= f.label :email, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
                <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email adress" %>
            </div>
          </div>
          
          <br>
          <div class="form-group row justify-content-center">
            <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg botonCE")%>
          </div>

        <% end %>
      </div>
      
      <div class="text-center mb-3">
        <%= link_to '[ Back to listing page ]', articles_path, method: :get, class: "btn btn-link text-info" %>
      </div>
    </div>
  </div>
</body>

app/views/users/edit.html.erb
<h1 class="text-black mt-4 text-center">Edit your profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4 ">Showing all users</h1>

<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user_path(user) %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text text-black"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to "View profile", user_path(user), class: "btn btn-outline-success" %>
            <% if logged_in? %> 
              <% if user == current_user %>
                <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
              <% end %>
              <% if current_user.admin? %>
                <%= link_to "Delete Profile", user_path(user), class: "btn btn-outline-danger", data: {"turbo-method": :delete, "turbo-confirm": "Estas seguro de eliminar todo lo asociado a este usuario?"} %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-body-secondary">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago. </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1 class="text-black mt-4 text-center">Sign up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-black mt-4 text-center"><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>
<% if logged_in? && @user == current_user %>
    <div class="text-center mt-4">
        <%= link_to "Edit profile", edit_user_path(@user), class: "btn btn-outline-info" %> 
    </div>
<% end %>

<h3 class="text-black mt-4 text-center">Articles</h3>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article', status: :unprocessable_entity %>